import "server-only";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * Where uploaded files are stored. The app only talks to this interface.
 *
 * - MEDIA_STORAGE=local (default): files in MEDIA_DIR (default ./data/uploads) – dev and single server
 * - MEDIA_STORAGE=s3: TODO – S3-compatible object storage (e.g. Hetzner Object Storage, EU region)
 */
export interface MediaStorage {
  put(key: string, data: Uint8Array): Promise<void>;
  get(key: string): Promise<Uint8Array | null>;
  delete(key: string): Promise<void>;
}

const SAFE_KEY = /^[A-Za-z0-9_-]+\.[a-z0-9]+$/; // keys are generated by us; never allow path tricks

function localDiskStorage(dir: string): MediaStorage {
  const resolve = (key: string) => {
    if (!SAFE_KEY.test(key)) throw new Error(`Invalid media key: ${key}`);
    return path.join(dir, key);
  };
  return {
    async put(key, data) {
      await mkdir(dir, { recursive: true });
      await writeFile(resolve(key), data);
    },
    async get(key) {
      try {
        return await readFile(resolve(key));
      } catch (e) {
        if ((e as NodeJS.ErrnoException).code === "ENOENT") return null;
        throw e;
      }
    },
    async delete(key) {
      await rm(resolve(key), { force: true });
    },
  };
}

export function getMediaStorage(): MediaStorage {
  const kind = process.env.MEDIA_STORAGE ?? "local";
  if (kind === "local") return localDiskStorage(path.resolve(process.env.MEDIA_DIR ?? "./data/uploads"));
  throw new Error(`Media storage "${kind}" is not implemented yet`);
}
